framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://redis:6379'
        pools:
            cache.rate_limiter:
                adapter: cache.adapter.redis
                provider: 'redis://redis:6379'
