framework:
    rate_limiter:
        api:
            policy: 'sliding_window'
            limit: 3
            interval: '1 minute'
            cache_pool: 'cache.rate_limiter'

services:
    cache.rate_limiter:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@Redis'
